### ISSUE TITLE
[BUG] Function parameter and variable values are shared between recursive function calls

### ISSUE THREAD

**Issue by frendsick** [frendsick/torth#54]
**Describe the bug**
Function parameter and variable values are shared between recursive function calls. This is a problem, at least if the function has multiple recursive calls to itself. This happens because each function's function parameters and variables are statically named memory locations. 

**To Reproduce**
1. Compile and run the example program below `./torth -r fibonacci.torth`
2. It prints wrong values to both its parameter `num` and the variable `variable`

```
include "std"
function Fib num:int -> int :
  NULL take variable in
  if num 1 <= do num return endif

  num 1 - Fib
  1337 variable =
  num 2 - Fib +

  // Expected variable value: 1337
  // Got: NULL
  "Variable value is: " puts
  variable print "\n" puts
end

function main :
  // Expected: 55
  // Got: 18446744073709551536
  10 Fib print
end
```

**Expected behavior**
Variables and function parameters should be separate for each recursive function call.

**Screenshots**

The output of the example program

![image](https://user-images.githubusercontent.com/44954973/204889939-a8cc8164-aa50-4d29-9249-23f574bfe510.png)

The function parameters and variables are statically named memory locations in Assembly.

![image](https://user-images.githubusercontent.com/44954973/204890317-2740d56a-c6e0-4827-b155-caca0e1eb16d.png)

**Additional context**
We would need a way to have parameters that are not statically named in the assembly. For example, in C, this is done by pushing each variable to the stack, but I am not sure if that is feasible in the already stack-based language. Maybe?

**Comment by CyberPaddy** [comment]
We could try using another stack for the local variables, the "locals stack".

All of the named parameters of the function are stored in `Func` object's `variables` attribute and so they could be pushed to the "locals stack" in order when the function is called. Also, all of the variables initialized by TAKE or PEEK blocks are stored in the same way.

We need to somehow bind each local variable name with certain position/offset in the locals stack. Then when the variable name is used as a token the value is loaded from the corresponding position of the locals stack to program's data stack. Here we could use similar logic as NTH intrinsic and just copy the Nth value from the locals stack and push it to the data stack.

Whenever a function is called we push its parameters and variables to the locals stack. Then whenever a function returns we drop as many items from the stack as the function has variables and parameters in total. This way all of the function calls have separate stacks of variables.

This solution will increase resource usage for nested or recursive functions. If this is too resource intensive solution we have to try something else or try optimizing it somehow.

I got the idea from Forth: https://forums.atariage.com/topic/273092-forth-local-variables-for-the-common-man/

**Comment by frendsick** [comment]
The implementation of local variables in #58 broke variable definitions of `TAKE` and `PEEK` blocks within `WHILE` blocks. I decided to rebase the local variable-related commits out of the `main` branch. The current language design does not seem to allow for local variable definitions within loops, as the loops do not store any information about how many variables are defined within them. Thus, we cannot know if the `TAKE` or `PEEK` block should increment the return stack pointer or overwrite the existing variable.
